### ISSUE TITLE
Decide what we want to be compatible with.

### ISSUE THREAD

**Issue by lukaszgo1** [SugarCaneNS/latex-access#7]
Before any big changes it would be good to decide about compatibility. Do we need to still be compatible with Python 2, and by extensions with  versions of NVDA earlier than 2019.3? It is reasonable to expect that when we would release anything 2019.3 would be already out.

**Comment by SugarCaneNS** [comment]
I think it would be reasonable to try to keep compatibility as much as possible between Python 2 and 3.  I believe I have already achieved this concerning the registered COM objects.  As for NVDA itself, I am unsure as to what extent we will be able to guarantee functionality with earlier versions.

**Comment by JulienCochuyt** [comment]
@lukaszgo1: Last time we discussed this question with @SugarCaneNS, we settled on trying to maintain backwards compatibility at least to NVDA 2018.2.1 - as many Windows 7 32 bits users are stuck there.
One tricky aspect is sometimes integration with NVDA UI itself (settings, ...) but I can provide 
code taken from WebAccess in that matter.

**Comment by lukaszgo1** [comment]
@JulienCochuyt I was not aware about any significant problems for Win 7 x32 users with more recent versions of NVDA. Are there any issues on NVDA bug tracker. My personal opinion is that we should not care about versions earlier than 2019.3 because  for older NVDA releases the current appModule or add-on from Derek Riemer are a viable solutions.

**Comment by JulienCochuyt** [comment]
> @JulienCochuyt I was not aware about any significant problems for Win 7 x32 users with more recent versions of NVDA. Are there any issues on NVDA bug tracker.

Sadly nothing documented enough to help properly addressing the issues.
We've had numerous reports from corporate users who were facing different types of instabilities on Windows 7 32 bits with all later NVDA versions, but were not given the means to investigate further. Most of the impacted systems are on the process of being renewed.

> My personal opinion is that we should not care about versions earlier than 2019.3 because for older NVDA releases the current appModule or add-on from Derek Riemer are a viable solutions.

That makes sense.

**Comment by JulienCochuyt** [comment]
Feel free to re-open if need be.
